spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/prac
  username: root
  password: Lisheng114

spring:
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update
     
server:
  port: 8080
  
security:
  secret: "SecretKeyToGenJWTs"
  EXPIRATION_TIME: 3600
  TOKEN_PREFIX: "Bearer "
  HEADER_STRING: "Authorization"
  SIGN_UP_URL: "/user/register"
  
info:
  name: "demo"
  description: "demoApp"
  
    