spring.datasource:
  platform: org.hibernate.dialect.PostgreSQL9Dialect
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost/jdbcdb?currentSchema=jdbc
  username: lisheng
  password: Lisheng114

spring:
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
     
server:
  port: 8080
  
security:
  secret: "SecretKeyToGenJWTs"
  EXPIRATION_TIME: 3600
  TOKEN_PREFIX: "Bearer "
  HEADER_STRING: "Authorization"
  SIGN_UP_URL: "/user/register"